routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'PagesController@home')->name('home');

Route::get('/culture', 'PagesController@blogLanding')->name('culture');
Route::get('/culture/article/{id}/{slug?}', 'PagesController@blogItem')->name('article');
Route::get('/culture/{category}', 'PagesController@blogcatagory')->name('category');
Route::get('/about', 'PagesController@about')->name('about');
Route::get('/clubs', 'PagesController@clubs')->name('clubs');
Route::get('/club/{id}/{slug?}', 'PagesController@club')->name('club');
//Route::get('/contact', 'PagesController@contact')->name('contact');

Route::get('/search', 'SearchController@Search');


Auth::routes();
Route::get('/dashboard', 'HomeController@index')->name('dashboard')->middleware('auth');;
Route::resource('dashboard/category','CategoryController')->middleware('auth');
Route::resource('dashboard/clubs', 'ClubController')->middleware('auth');
Route::resource('dashboard/events', 'EventController')->middleware('auth');
Route::resource('dashboard/users', 'UserController')->middleware('auth');
Route::resource('dashboard/locations', 'LocationController')->middleware('auth');
Route::resource('dashboard/articles', 'ArticleController')->middleware('auth');
Route::resource('dashboard/content', 'ContentController')->middleware('auth');

app/Club.php
<?php

namespace fitness;

use Illuminate\Database\Eloquent\Model;

class Club extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'clubs';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = ['Activity', 'Community', 'About', 'Activity_image', 'Activity_link', 'Activity_content'];

    public function events()
    {
        return $this->hasMany('fitness\Events');
    }

    public function colour()
    {
        return $this->belongsTo('fitness\Category', 'category', 'category');

    }

}

app/Http/Controllers/ClubController.php
<?php

namespace fitness\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Validator;

use fitness\Club;
use fitness\Category;
use fitness\Location;

class ClubController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
       $clubs=  Club::all();


        return view('Dashboard.club.index', compact('clubs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        $categories =  Category::all();
        $locations =  Location::all();
        return view('Dashboard.club.create', compact('categories','locations'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {


        $validator =  $request->validate([

            ]);
            $validator = Validator::make($request->all(), [
             'category' => 'required',
			'name' => 'required',
			'description' => 'required',
			'logo' => 'required'
            ]);


            if ($validator->fails()){
                \Session::flash('Warning', 'Please enter the valid details');
                return Redirect::to('/dashboard/clubs')->withInput()->withErrors($validator);
            }

            $club = new Club;
            $club->category = $request['category'];
            $club->name = $request['name'];
            $club->location = $request['location'];
            $club->description = $request['description'];
            $club->logo = $request['logo'];

            $club->save();

            \Session::flash('success', 'Club added successfully');


        return redirect('/dashboard/clubs')->with('success', 'Club added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $club = Club::findOrFail($id);

        return view('Dashboard.club.index', compact('club'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {

        $club = Club::find($id);
        $locations =  Location::all();
        $categories =  Category::all();
        $activities = Category::groupBy('category')->pluck('category','category');

        return view('Dashboard.club.edit', compact('club' , 'activities', 'categories','id','locations'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */

        public function update(Request $request, $id)
        {
            $locations =  Location::all();
            $categories =  Category::all();
            $activities = Category::groupBy('category')->pluck('category','category');

            $club = Club::find($id);
            $club->location = $request['location'];
            $club->category = $request['category'];
            $club->name = $request['name'];
            $club->description = $request['description'];
            $club->logo = $request['logo'];

            $club->save();

               return view('Dashboard.club.edit', compact('club' , 'activities', 'categories','id','locations'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        Club::destroy($id);

        return redirect('/dashboard/clubs')->with('flash_message', 'Club deleted!');
    }
}

resources/views/Dashboard/club/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                <div class="card-header">
                            <div class="row justify-content-center">
                            <div class="col-md-12">
                        <h1><a href="{{ route('dashboard') }}">FFL Dashboard  | </a/><a href="{{ route('clubs.index') }}">Club</a/> | Create a new club</h1>
                    </div>

                    </div>

                    </div>



                <div class="card-body">




                    <form method="post" action="{{action('ClubController@store')}}">
        @csrf

       <div class="row">
         <div class="col-md-6 ">

                <div class="row">

                <div class="form-group col-md-12">
                    <label>Activity</label>
                    <select name="category" class="form-control">
                            @foreach($categories as $category)
                            <option value="{{$category->category}}" >{{$category->category}}</option>

                            @endforeach

                    </select>
                </div>

            <div class="form-group col-md-12 ">
              <label>Community:</label>
              <input type="text" class="form-control" name="name" value="" required>
            </div>


                   <div class="form-group col-md-12 ">
                       <label>Location</label>

                       <select name="location" class="form-control">
                            @foreach($locations as $location)
                            <option value="{{$location->location}}" >{{$location->location}}</option>

                            @endforeach

                    </select>

                   </div>



               <div class="form-group col-md-12 ">
                    <label>Logo</label>
                <div class="input-group">
                    <span class="input-group-btn">
                      <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                        <i class="fa fa-picture-o"></i> Choose
                      </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="logo" required >
                  </div>
                  <img id="holder" style="margin-top:15px;max-height:100px;">
              </div>

              <div class="form-group col-md-12">
                    <button type="submit" class="btn btn-success">Submit</button>
                  </div>

             </div>
         </div>


                <div class="col-md-6">
                  <div class="form-group  ">
                      <label>About:</label>
                      <textarea rows=9 class="form-control my-editor" name="description"></textarea>
                    </div>
                  </div>

       </div>

      </form>
      </div>


    </div>
</div>
</div>
</div>


@endsection

resources/views/Dashboard/club/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">

                    <div class="card-header">
                            <div class="row justify-content-center">
                            <div class="col-md-12">
                        <h1><a href="{{ route('dashboard') }}">FFL Dashboard  | </a/><a href="{{ route('clubs.index') }}">Clubs</a/> | Edit {{$club->name}}</h1>
                    </div>

                    </div>

                    </div>

                <div class="card-body">


                    @if (\Session::has('success'))
                    <div class="alert alert-success">
                      <p>{{ \Session::get('success') }}</p>
                    </div><br />
                   @endif

                   <div class="row justify-content-center">

<div class="table-responsive col-md-6">
        <table class="table">
            <tbody>

                <tr><th> Activity </th><td> {{ $club->category }} </td></tr>
                <tr><th> Community </th><td>{{$club->name}}</td></tr>
                <tr><th> Location </th><td>{{$club->location}}</td></tr>

               <tr><th> Image </th><td><img src="{{ $club->logo }}" class="img-thumbnail" style= "width:auto; height:100px;"/></td></tr>

            </tbody>
        </table>
    </div>
        <div class="table-responsive col-md-6">
                <table class="table">
                    <tbody>
        <tr><th> About </th><td>@php Print_r($club->description);@endphp</td></tr>

    </tbody>
</table>
    </div>
                   </div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#editModal">
  Edit {{$club->name}}
</button>


<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="ModalLabel">Edit {{$club->name}}</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">




            <form method="post" action="{{action('ClubController@update', $id)}}">
                    @csrf
                    <input name="_method" type="hidden" value="PATCH">

           <div class="row">

                  <div class="form-group col-md-6">
                    <label>Activity</label>
                  <select name="category" class="form-control">
                      <option value="{{$club->category}}" >{{$club->category}}</option>

                       @foreach($categories as $category)
                              <option value="{{$category->category}}" >{{$category->category}}</option>
                        @endforeach
                     </select>
                    </div>

                <div class="form-group col-md-6">
                  <label>Community:</label>
                  <input type="text" class="form-control" name="name" value="{{$club->name}}">
                </div>

                <div class="form-group col-md-6">
                <label>Location</label>


                <select name="location" class="form-control">
                        <option value="{{$club->location}}" >{{$club->location}}</option>

                        @foreach($locations as $location)
                        <option value="{{$location->location}}" >{{$location->location}}</option>

                        @endforeach
                       </select>


           </div>

                <div class="form-group col-md-6">
                        <label>Logo:</label>
                        <div class="input-group">
                            <span class="input-group-btn">
                              <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                                <i class="fa fa-picture-o"></i> Choose
                              </a>
                            </span>
                            <input id="thumbnail" class="form-control" type="text" name="logo" value="{{$club->logo}}">
                          </div>
                          <img id="holder" style="margin-top:15px;max-height:100px;">
                  </div>

                <div class="form-group col-md-12">
                          <label for="Community">About:</label>
                          <textarea class="form-control my-editor" name="description">{{$club->description}}</textarea>
                        </div>



                        <div class="form-group col-md-12">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

            </div>
          </div>
        </div>
      </div>

      </div>

    </div>
</div>
</div>
</div>


@endsection

resources/views/Dashboard/club/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">

                        <div class="card-header">
                                <div class="row justify-content-center">
                                <div class="col-md-8">
                          <h1>  <a href="{{ route('dashboard') }}">FFL Dashboard | </a/> Articles</h1>

                        </div>
                            <div class="col-md-4">
                                    <h1><a class="pull-right" href="{{ route('clubs.create') }}">Add a new club</a></h1>
                            </div>
                        </div>

                        </div>



                    <div class="card-body">



                                @if (\Session::has('success'))
                                  <div class="alert alert-success">
                                    <p>{{ \Session::get('success') }}</p>
                                  </div><br />
                                 @endif

                                <table class="table table-striped">
                                <thead>
                                  <tr>
                                    <th>ID</th>
                                    <th>Activity </th>
                                    <th>Community</th>

                                    <th colspan="2">Action</th>
                                  </tr>
                                </thead>
                                <tbody>

                                  @foreach($clubs as $club)

                                  <tr>
                                    <td>{{ $club->id }}</td>
                                    <td>{{ $club->category }}</td>
                                    <td>{{$club->name}}</td>


                                    <td><a href="{{action('ClubController@edit', $club['id'])}}" class="btn btn-warning">Edit</a></td>
                                    <td>
                                      <form action="{{action('ClubController@destroy', $club['id'])}}" method="post">
                                        @csrf
                                        <input name="_method" type="hidden" value="DELETE">
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                      </form>
                                    </td>
                                  </tr>
                                  @endforeach
                                </tbody>
                              </table>
                              </div>

                            </div>


                        </div>
                    </div>
               </div>
           </div>
                              @endsection